import assert from "node:assert/strict";
import { test } from "node:test";
import type { Run } from "../src/board.ts";
import { captureLogic, logicArgs, summarizeCsv, summarizeDecoded } from "../src/logic.ts";

test("sigrok-cli arguments: raw capture as CSV, or a decoder with its annotations", () => {
  assert.deepEqual(logicArgs({ driver: "fx2lafw" }, {}), ["-d", "fx2lafw", "--config", "samplerate=1m", "--time", "500", "-O", "csv"]);
  assert.deepEqual(
    logicArgs({ driver: "fx2lafw", samplerate: "4m", channels: "D0,D1" }, { seconds: 0.2, decoder: "i2c:scl=D0:sda=D1", trigger: "D0=f" }),
    ["-d", "fx2lafw", "--config", "samplerate=4m", "--time", "200", "-C", "D0,D1", "-t", "D0=f", "-w", "-P", "i2c:scl=D0:sda=D1", "-A", "i2c"],
  );
  assert.equal(logicArgs({ driver: "demo" }, { seconds: 60 })[5], "10000", "at most 10 s");
});

test("a raw capture becomes per-channel levels, edges and frequency", () => {
  const csv = ["; CSV, generated by sigrok-cli", "; Channels (2/8): D0, D1", "D0,D1",
    ...Array.from({ length: 1000 }, (_, i) => `${Math.floor(i / 5) % 2},0`)].join("\n");
  const s = summarizeCsv(csv, 0.001, { D0: "SCL", D1: "SDA" });
  assert.match(s, /^1000 samples over 0\.001 s:/);
  assert.match(s, /- D0 \(SCL\): 50% high, 199 edges, ≈ 99\.5 kHz/);
  assert.match(s, /- D1 \(SDA\): stuck low/);
  assert.equal(summarizeCsv("; nothing\n", 1), "The capture holds no samples.");
});

test("decoded traffic is listed and counted by kind", () => {
  const s = summarizeDecoded("i2c-1: Start\ni2c-1: Address write: 68\ni2c-1: ACK\ni2c-1: Data write: 7E\ni2c-1: ACK\ni2c-1: Stop\n");
  assert.match(s, /^6 annotations\. By kind: ACK ×2, Start ×1, Address write ×1/);
  assert.match(s, /i2c-1: Address write: 68/);
  assert.match(summarizeDecoded(""), /decoder found nothing/);
});

/** sigrok-cli as a fake: installed or not, with canned answers. */
const fake = (installed: boolean, answers: Record<string, string> = {}): Run & { seen: string[][] } => {
  const seen: string[][] = [];
  const run = (async (command: string, args: string[]) => {
    seen.push([command, ...args]);
    const line = [command, ...args].join(" ");
    if (line.includes("command -v sigrok-cli")) return { stdout: installed ? "/opt/homebrew/bin/sigrok-cli\n" : "", stderr: "", code: installed ? 0 : 1 };
    for (const [key, out] of Object.entries(answers)) if (line.includes(key)) return { stdout: out, stderr: "", code: 0 };
    return { stdout: "", stderr: "", code: 0 };
  }) as Run & { seen: string[][] };
  run.seen = seen;
  return run;
};

test("without sigrok-cli, or without a configured analyzer, it says what to do", async () => {
  assert.match(await captureLogic(fake(false), "/p", {}, {}), /sigrok-cli is not installed.*brew install sigrok-cli/s);
  const scan = await captureLogic(fake(true, { "--scan": "fx2lafw - Saleae Logic with 8 channels: D0 D1 D2 D3 D4 D5 D6 D7\n" }), "/p", {}, {});
  assert.match(scan, /No logic analyzer set.*fx2lafw - Saleae Logic/s);
});

test("a decoded capture runs sigrok-cli with the decoder and summarizes it", async () => {
  const run = fake(true, { "'-P' 'i2c": "i2c-1: Start\ni2c-1: Address read: 68\ni2c-1: NACK\ni2c-1: Stop\n" });
  const out = await captureLogic(run, "/p", { driver: "fx2lafw" }, { decoder: "i2c:scl=D0:sda=D1", seconds: 0.1 });
  assert.match(out, /^Logic capture \(fx2lafw, 1m samples\/s, 0\.1 s\):/);
  assert.match(out, /NACK ×1/);
  assert.ok(run.seen.some(c => c.join(" ").includes("sigrok-cli '-d' 'fx2lafw'")));
});
